services:
  - type: web
    name: antigravity-backend
    runtime: python
    region: singapore # Optional, pick closest
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 8
    envVars:
      - key: PORT
        value: 10000
